const CarConstants = [
  'Dinghy',
  'Dinghy2',
  'Dinghy3',
  'Dinghy4',
  'Jetmax',
  'Marquis',
  'Seashark',
  'Seashark2',
  'Seashark3',
  'Speeder',
  'Speeder2',
  'Squalo',
  'Submersible',
  'Submersible2',
  'Suntrap',
  'Toro',
  'Toro2',
  'Tropic',
  'Tropic2',
  'Tug',
  'Benson',
  'Biff',
  'Hauler',
  'Hauler2',
  'Mule',
  'Mule2',
  'Mule3',
  'Packer',
  'Phantom',
  'Phantom2',
  'Phantom3',
  'Pounder',
  'Stockade',
  'Stockade3',
  'Blista',
  'Blista2',
  'Blista3',
  'Brioso',
  'Dilettante',
  'Dilettante2',
  'Issi2',
  'Panto',
  'Prairie',
  'Rhapsody',
  'Cog Cabrio',
  'Exemplar',
  'F620',
  'Felon',
  'Felon2',
  'Jackal',
  'Oracle',
  'Oracle2',
  'Sentinel',
  'Sentinel2',
  'Windsor',
  'Windsor2',
  'Zion',
  'Zion2',
  'Bmx',
  'Cruiser',
  'Fixter',
  'Scorcher',
  'Tri Bike',
  'Tri Bike2',
  'Tri Bike3',
  'Ambulance',
  'FBI',
  'FBI2',
  'Fire Truck',
  'PBus',
  'Police',
  'Police2',
  'Police3',
  'Police4',
  'Police Old1',
  'Police Old2',
  'Police T',
  'Policeb',
  'Polmav',
  'Pranger',
  'Predator',
  'Riot',
  'Sheriff',
  'Sheriff2',
  'Annihilator',
  'Buzzard',
  'Buzzard2',
  'Cargobob',
  'Cargobob2',
  'Cargobob3',
  'Cargobob4',
  'Frogger',
  'Frogger2',
  'Maverick',
  'Savage',
  'Skylift',
  'Supervolito',
  'Supervolito2',
  'Swift',
  'Swift2',
  'Valkyrie',
  'Valkyrie2',
  'Volatus',
  'Bulldozer',
  'Cutter',
  'Dump',
  'Flatbed',
  'Guardian',
  'Handler',
  'Mixer',
  'Mixer2',
  'Rubble',
  'Tip Truck',
  'Tip Truck2',
  'APC',
  'Barracks',
  'Barracks2',
  'Barracks3',
  'Crusader',
  'Halftrack',
  'Rhino',
  'Trailersmall2',
  'Akuma',
  'Avarus',
  'Bagger',
  'Bati2',
  'Bati',
  'BF400',
  'Blazer4',
  'Carbon RS',
  'Chimera',
  'Cliffhanger',
  'Daemon2',
  'Daemon',
  'Defiler',
  'Double',
  'Enduro',
  'Esskey',
  'Faggio',
  'Faggio2',
  'Faggio3',
  'Fcr2',
  'Fcr',
  'Gargoyle',
  'Hakuchou2',
  'Hakuchou',
  'Hexer',
  'Innovation',
  'Lectro',
  'Manchez',
  'Nemesis',
  'Nightblade',
  'Opressor',
  'PCJ',
  'Ratbike',
  'Ruffian',
  'Sanchez2',
  'Sanchez',
  'Sanctus',
  'Shotaro',
  'Sovereign',
  'Thrust',
  'Vader',
  'Vindicator',
  'Vortex',
  'Wolfsbane',
  'Zombiea',
  'Zombieb',
  'Blade',
  'Buccaneer',
  'Buccaneer2',
  'Chino',
  'Chino2',
  'Dominator',
  'Dominator2',
  'Dukes',
  'Dukes2',
  'Faction',
  'Faction2',
  'Faction3',
  'Gauntlet',
  'Gauntlet2',
  'Hotknife',
  'Lurcher',
  'Moonbeam',
  'Moonbeam2',
  'Nightshade',
  'Phoenix',
  'Picador',
  'Rat Loader',
  'Rat Loader2',
  'Ruiner',
  'Ruiner2',
  'Sabre GT',
  'Sabre GT2',
  'Sadler2',
  'Slam Van',
  'Slam Van2',
  'Slam Van3',
  'Stalion',
  'Stalion2',
  'Tampa',
  'Tampa3',
  'Vigero',
  'Virgo',
  'Virgo2',
  'Virgo3',
  'Voodoo',
  'Voodoo2',
  'Bf Injection',
  'Bifta',
  'Blazer',
  'Blazer2',
  'Blazer3',
  'Blazer5',
  'Bodhi2',
  'Brawler',
  'DLoader',
  'Dune',
  'Dune2',
  'Dune3',
  'Dune4',
  'Dune5',
  'Insurgent',
  'Insurgent2',
  'Insurgent3',
  'Kalahari',
  'Lguard',
  'Marshall',
  'Mesa',
  'Mesa2',
  'Mesa3',
  'Monster',
  'Nightshark',
  'Rancher XL',
  'Rancher XL2',
  'Rebel',
  'Rebel2',
  'Sandking',
  'Sandking2',
  'Technical',
  'Technical2',
  'Technical3',
  'Trophy Truck',
  'Trophy Truck2',
  'Besra',
  'Blimp',
  'Blimp2',
  'Cargo Plane',
  'Cuban800',
  'Dodo',
  'Duster',
  'Hydra',
  'Jet',
  'Lazer',
  'Luxor',
  'Luxor2',
  'Mammatus',
  'Miljet',
  'Nimbus',
  'Shamal',
  'Stunt',
  'Titan',
  'Velum',
  'Velum2',
  'Vestra',
  'BJXL',
  'Baller',
  'Baller2',
  'Baller3',
  'Baller4',
  'Baller5',
  'Baller6',
  'Cavalcade',
  'Cavalcade2',
  'Contender',
  'Dubsta',
  'Dubsta2',
  'Dubsta3',
  'FQ2',
  'Granger',
  'Gresley',
  'Habanero',
  'Huntley',
  'Landstalker',
  'Patriot',
  'Radi',
  'Rocoto',
  'Seminole',
  'Serrano',
  'XLS',
  'XLS2',
  'Asea',
  'Asea2',
  'Asterope',
  'Cog55',
  'Cog552',
  'Cognoscenti',
  'Cognoscenti2',
  'Emperor',
  'Emperor2',
  'Emperor3',
  'Fugitive',
  'Glendale',
  'Ingot',
  'Intruder',
  'Limo2',
  'Premier',
  'Primo',
  'Primo2',
  'Regina',
  'Romero',
  'Stanier',
  'Stratum',
  'Stretch',
  'Surge',
  'Tailgater',
  'Warrener',
  'Washington',
  'Airbus',
  'Brickade',
  'Bus',
  'Coach',
  'Rallytruck',
  'Rental Bus',
  'Taxi',
  'Tourbus',
  'Trash',
  'Trash2',
  'Alpha',
  'Banshee',
  'Banshee2',
  'Bestia GTS',
  'Buffalo',
  'Buffalo2',
  'Buffalo3',
  'Carbonizzare',
  'Comet2',
  'Comet3',
  'Coquette',
  'Elegy',
  'Elegy2',
  'Feltzer2',
  'Feltzer3',
  'Furoregt',
  'Fusilade',
  'Futo',
  'Infernus2',
  'Jester',
  'Jester2',
  'Khamelion',
  'Kuruma',
  'Kuruma2',
  'Lynx',
  'Massacro',
  'Massacro2',
  'Ninef',
  'Ninef2',
  'Omnis',
  'Penumbra',
  'Rapid GT',
  'Rapid GT2',
  'Raptor',
  'Ruston',
  'Schafter2',
  'Schafter3',
  'Schafter4',
  'Schafter5',
  'Schafter6',
  'Schwarzer',
  'Seven70',
  'Specter',
  'Specter2',
  'Sultan',
  'Surano',
  'Tampa2',
  'Tropos',
  'Verlierer2',
  'Ardent',
  'BType',
  'BType2',
  'BType3',
  'Casco',
  'Cheetah2',
  'Coquette2',
  'Coquette3',
  'JB700',
  'Mamba',
  'Manana',
  'Monroe',
  'Peyote',
  'Pigalle',
  'Stinger',
  'Stinger GT',
  'Torero',
  'Tornado',
  'Tornado2',
  'Tornado3',
  'Tornado4',
  'Tornado5',
  'Tornado6',
  'ZType',
  'Adder',
  'Bullet',
  'Cheetah',
  'Entity XF',
  'FMJ',
  'GP1',
  'Infernus',
  'RE7B',
  'Nero',
  'Nero2',
  'Osiris',
  'Penetrator',
  'Pfister811',
  'Prototipo',
  'Reaper',
  'Sheava',
  'Sultan RS',
  'Superd',
  'T20',
  'Tempesta',
  'Turismo2',
  'Turismor',
  'Tyrus',
  'Vacca',
  'Vagner',
  'Voltic',
  'Voltic2',
  'Zentorno',
  'Italigtb',
  'Italigtb2',
  'XA21',
  'Army Tanker',
  'Army Trailer',
  'Army Trailer2',
  'Bale Trailer',
  'Boat Trailer',
  'Cable Car',
  'Dock Trailer',
  'Grain Trailer',
  'Prop Trailer',
  'Rake Trailer',
  'TR2',
  'TR3',
  'TR4',
  'TRFlat',
  'TVTrailer',
  'Tanker',
  'Tanker2',
  'Trailer Logs',
  'Trailer Small',
  'Trailers',
  'Trailers2',
  'Trailers3',
  'Freight',
  'Freight Car',
  'Freight Cont1',
  'Freight Cont2',
  'Freight Grain',
  'Freight Trailer',
  'Tanker Car',
  'Airtug',
  'Caddy',
  'Caddy2',
  'Caddy3',
  'Docktug',
  'Forklift',
  'Mower',
  'Ripley',
  'Sadler',
  'Scrap',
  'Tow Truck',
  'Tow Truck2',
  'Tractor',
  'Tractor2',
  'Tractor3',
  'Trailer Large',
  'Trailer S4',
  'Utilli Truck',
  'Bison',
  'Bison2',
  'Bison3',
  'Bobcat XL',
  'Boxville',
  'Boxville2',
  'Boxville3',
  'Boxville4',
  'Boxville5',
  'Burrito',
  'Burrito2',
  'Burrito3',
  'Burrito4',
  'Burrito5',
  'Camper',
  'GBurrito',
  'GBurrito2',
  'Journey',
  'Minivan',
  'Minivan2',
  'Paradise',
  'Pony',
  'Pony2',
  'Rumpo',
  'Rumpo2',
  'Rumpo3',
  'Speedo',
  'Speedo2',
  'Surfer',
  'Surfer2',
  'Taco',
  'Youga',
  'Youga2',
];

const Weapons = {
  melee: {
    dagger: '0x92A27487',
    bat: '0x958A4A8F',
    bottle: '0xF9E6AA4B',
    crowbar: '0x84BD7BFD',
    unarmed: '0xA2719263',
    flashlight: '0x8BB05FD7',
    golfclub: '0x440E4788',
    hammer: '0x4E875F73',
    hatchet: '0xF9DCBF2D',
    knuckle: '0xD8DF3C3C',
    knife: '0x99B507EA',
    machete: '0xDD5DF8D9',
    switchblade: '0xDFE37640',
    nightstick: '0x678B81B1',
    wrench: '0x19044EE0',
    battleaxe: '0xCD274149',
    poolcue: '0x94117305',
    stone_hatchet: '0x3813FC08',
  },
  handguns: {
    pistol: '0x1B06D571',
    pistol_mk2: '0xBFE256D4',
    combatpistol: '0x5EF9FEC4',
    appistol: '0x22D8FE39',
    stungun: '0x3656C8C1',
    pistol50: '0x99AEEB3B',
    snspistol: '0xBFD21232',
    snspistol_mk2: '0x88374054',
    heavypistol: '0xD205520E',
    vintagepistol: '0x83839C4',
    flaregun: '0x47757124',
    marksmanpistol: '0xDC4DB296',
    revolver: '0xC1B3C3D1',
    revolver_mk2: '0xCB96392F',
    doubleaction: '0x97EA20B8',
    raypistol: '0xAF3696A1',
    ceramicpistol: '0x2B5EF5EC',
    navyrevolver: '0x917F6C8C',
  },
  smg: {
    microsmg: '0x13532244',
    smg: '0x2BE6766B',
    smg_mk2: '0x78A97CD0',
    assaultsmg: '0xEFE7E2DF',
    combatpdw: '0xA3D4D34',
    machinepistol: '0xDB1AA450',
    minismg: '0xBD248B55',
    raycarbine: '0x476BF155',
  },
  shotguns: {
    pumpshotgun: '0x1D073A89',
    pumpshotgun_mk2: '0x555AF99A',
    sawnoffshotgun: '0x7846A318',
    assaultshotgun: '0xE284C527',
    bullpupshotgun: '0x9D61E50F',
    musket: '0xA89CB99E',
    heavyshotgun: '0x3AABBBAA',
    dbshotgun: '0xEF951FBB',
    autoshotgun: '0x12E82D3D',
  },
  assault_rifles: {
    assaultrifle: '0xBFEFFF6D',
    assaultrifle_mk2: '0x394F415C',
    carbinerifle: '0x83BF0278',
    carbinerifle_mk2: '0xFAD1F1C9',
    advancedrifle: '0xAF113F99',
    specialcarbine: '0xC0A3098D',
    specialcarbine_mk2: '0x969C3D67',
    bullpuprifle: '0x7F229F94',
    bullpuprifle_mk2: '0x84D6FAFD',
    compactrifle: '0x624FE830',
  },
  machine_guns: {
    mg: '0x9D07F764',
    combatmg: '0x7FD62962',
    combatmg_mk2: '0xDBBD7280',
    gusenberg: '0x61012683',
  },
  sniper_rifles: {
    sniperrifle: '0x5FC3C11',
    heavysniper: '0xC472FE2',
    heavysniper_mk2: '0xA914799',
    marksmanrifle: '0xC734385A',
    marksmanrifle_mk2: '0x6A6C02E0',
  },
  heavy_weapons: {
    rpg: '0xB1CA77B1',
    grenadelauncher: '0xA284510B',
    grenadelauncher_smoke: '0x4DD2DC56',
    minigun: '0x42BF8A85',
    firework: '0x7F7497E5',
    railgun: '0x6D544C99',
    hominglauncher: '0x63AB0442',
    compactlauncher: '0x781FE4A',
    rayminigun: '0xB62D1F67',
  },
  throwables: {
    grenade: '0x93E220BD',
    bzgas: '0xA0973D5E',
    smokegrenade: '0xFDBC8A50',
    flare: '0x497FACC3',
    molotov: '0x24B17070',
    stickybomb: '0x2C3731D9',
    proxmine: '0xAB564B93',
    snowball: '0x787F0BB',
    pipebomb: '0xBA45E8B8',
    ball: '0x23C9F95C',
  },
  misc: {
    petrolcan: '0x34A67B97',
    fireextinguisher: '0x60EC506',
    parachute: '0xFBAB5776',
    hazardcan: '0xBA536372',
  },
};

export { CarConstants, Weapons };
