const CarConstants = [
  'Dinghy',
  'Dinghy2',
  'Dinghy3',
  'Dinghy4',
  'Jetmax',
  'Marquis',
  'Seashark',
  'Seashark2',
  'Seashark3',
  'Speeder',
  'Speeder2',
  'Squalo',
  'Submersible',
  'Submersible2',
  'Suntrap',
  'Toro',
  'Toro2',
  'Tropic',
  'Tropic2',
  'Tug',
  'Benson',
  'Biff',
  'Hauler',
  'Hauler2',
  'Mule',
  'Mule2',
  'Mule3',
  'Packer',
  'Phantom',
  'Phantom2',
  'Phantom3',
  'Pounder',
  'Stockade',
  'Stockade3',
  'Blista',
  'Blista2',
  'Blista3',
  'Brioso',
  'Dilettante',
  'Dilettante2',
  'Issi2',
  'Panto',
  'Prairie',
  'Rhapsody',
  'Cog Cabrio',
  'Exemplar',
  'F620',
  'Felon',
  'Felon2',
  'Jackal',
  'Oracle',
  'Oracle2',
  'Sentinel',
  'Sentinel2',
  'Windsor',
  'Windsor2',
  'Zion',
  'Zion2',
  'Bmx',
  'Cruiser',
  'Fixter',
  'Scorcher',
  'Tri Bike',
  'Tri Bike2',
  'Tri Bike3',
  'Ambulance',
  'FBI',
  'FBI2',
  'Fire Truck',
  'PBus',
  'Police',
  'Police2',
  'Police3',
  'Police4',
  'Police Old1',
  'Police Old2',
  'Police T',
  'Policeb',
  'Polmav',
  'Pranger',
  'Predator',
  'Riot',
  'Sheriff',
  'Sheriff2',
  'Annihilator',
  'Buzzard',
  'Buzzard2',
  'Cargobob',
  'Cargobob2',
  'Cargobob3',
  'Cargobob4',
  'Frogger',
  'Frogger2',
  'Maverick',
  'Savage',
  'Skylift',
  'Supervolito',
  'Supervolito2',
  'Swift',
  'Swift2',
  'Valkyrie',
  'Valkyrie2',
  'Volatus',
  'Bulldozer',
  'Cutter',
  'Dump',
  'Flatbed',
  'Guardian',
  'Handler',
  'Mixer',
  'Mixer2',
  'Rubble',
  'Tip Truck',
  'Tip Truck2',
  'APC',
  'Barracks',
  'Barracks2',
  'Barracks3',
  'Crusader',
  'Halftrack',
  'Rhino',
  'Trailersmall2',
  'Akuma',
  'Avarus',
  'Bagger',
  'Bati2',
  'Bati',
  'BF400',
  'Blazer4',
  'Carbon RS',
  'Chimera',
  'Cliffhanger',
  'Daemon2',
  'Daemon',
  'Defiler',
  'Double',
  'Enduro',
  'Esskey',
  'Faggio',
  'Faggio2',
  'Faggio3',
  'Fcr2',
  'Fcr',
  'Gargoyle',
  'Hakuchou2',
  'Hakuchou',
  'Hexer',
  'Innovation',
  'Lectro',
  'Manchez',
  'Nemesis',
  'Nightblade',
  'Opressor',
  'PCJ',
  'Ratbike',
  'Ruffian',
  'Sanchez2',
  'Sanchez',
  'Sanctus',
  'Shotaro',
  'Sovereign',
  'Thrust',
  'Vader',
  'Vindicator',
  'Vortex',
  'Wolfsbane',
  'Zombiea',
  'Zombieb',
  'Blade',
  'Buccaneer',
  'Buccaneer2',
  'Chino',
  'Chino2',
  'Dominator',
  'Dominator2',
  'Dukes',
  'Dukes2',
  'Faction',
  'Faction2',
  'Faction3',
  'Gauntlet',
  'Gauntlet2',
  'Hotknife',
  'Lurcher',
  'Moonbeam',
  'Moonbeam2',
  'Nightshade',
  'Phoenix',
  'Picador',
  'Rat Loader',
  'Rat Loader2',
  'Ruiner',
  'Ruiner2',
  'Sabre GT',
  'Sabre GT2',
  'Sadler2',
  'Slam Van',
  'Slam Van2',
  'Slam Van3',
  'Stalion',
  'Stalion2',
  'Tampa',
  'Tampa3',
  'Vigero',
  'Virgo',
  'Virgo2',
  'Virgo3',
  'Voodoo',
  'Voodoo2',
  'Bf Injection',
  'Bifta',
  'Blazer',
  'Blazer2',
  'Blazer3',
  'Blazer5',
  'Bodhi2',
  'Brawler',
  'DLoader',
  'Dune',
  'Dune2',
  'Dune3',
  'Dune4',
  'Dune5',
  'Insurgent',
  'Insurgent2',
  'Insurgent3',
  'Kalahari',
  'Lguard',
  'Marshall',
  'Mesa',
  'Mesa2',
  'Mesa3',
  'Monster',
  'Nightshark',
  'Rancher XL',
  'Rancher XL2',
  'Rebel',
  'Rebel2',
  'Sandking',
  'Sandking2',
  'Technical',
  'Technical2',
  'Technical3',
  'Trophy Truck',
  'Trophy Truck2',
  'Besra',
  'Blimp',
  'Blimp2',
  'Cargo Plane',
  'Cuban800',
  'Dodo',
  'Duster',
  'Hydra',
  'Jet',
  'Lazer',
  'Luxor',
  'Luxor2',
  'Mammatus',
  'Miljet',
  'Nimbus',
  'Shamal',
  'Stunt',
  'Titan',
  'Velum',
  'Velum2',
  'Vestra',
  'BJXL',
  'Baller',
  'Baller2',
  'Baller3',
  'Baller4',
  'Baller5',
  'Baller6',
  'Cavalcade',
  'Cavalcade2',
  'Contender',
  'Dubsta',
  'Dubsta2',
  'Dubsta3',
  'FQ2',
  'Granger',
  'Gresley',
  'Habanero',
  'Huntley',
  'Landstalker',
  'Patriot',
  'Radi',
  'Rocoto',
  'Seminole',
  'Serrano',
  'XLS',
  'XLS2',
  'Asea',
  'Asea2',
  'Asterope',
  'Cog55',
  'Cog552',
  'Cognoscenti',
  'Cognoscenti2',
  'Emperor',
  'Emperor2',
  'Emperor3',
  'Fugitive',
  'Glendale',
  'Ingot',
  'Intruder',
  'Limo2',
  'Premier',
  'Primo',
  'Primo2',
  'Regina',
  'Romero',
  'Stanier',
  'Stratum',
  'Stretch',
  'Surge',
  'Tailgater',
  'Warrener',
  'Washington',
  'Airbus',
  'Brickade',
  'Bus',
  'Coach',
  'Rallytruck',
  'Rental Bus',
  'Taxi',
  'Tourbus',
  'Trash',
  'Trash2',
  'Alpha',
  'Banshee',
  'Banshee2',
  'Bestia GTS',
  'Buffalo',
  'Buffalo2',
  'Buffalo3',
  'Carbonizzare',
  'Comet2',
  'Comet3',
  'Coquette',
  'Elegy',
  'Elegy2',
  'Feltzer2',
  'Feltzer3',
  'Furoregt',
  'Fusilade',
  'Futo',
  'Infernus2',
  'Jester',
  'Jester2',
  'Khamelion',
  'Kuruma',
  'Kuruma2',
  'Lynx',
  'Massacro',
  'Massacro2',
  'Ninef',
  'Ninef2',
  'Omnis',
  'Penumbra',
  'Rapid GT',
  'Rapid GT2',
  'Raptor',
  'Ruston',
  'Schafter2',
  'Schafter3',
  'Schafter4',
  'Schafter5',
  'Schafter6',
  'Schwarzer',
  'Seven70',
  'Specter',
  'Specter2',
  'Sultan',
  'Surano',
  'Tampa2',
  'Tropos',
  'Verlierer2',
  'Ardent',
  'BType',
  'BType2',
  'BType3',
  'Casco',
  'Cheetah2',
  'Coquette2',
  'Coquette3',
  'JB700',
  'Mamba',
  'Manana',
  'Monroe',
  'Peyote',
  'Pigalle',
  'Stinger',
  'Stinger GT',
  'Torero',
  'Tornado',
  'Tornado2',
  'Tornado3',
  'Tornado4',
  'Tornado5',
  'Tornado6',
  'ZType',
  'Adder',
  'Bullet',
  'Cheetah',
  'Entity XF',
  'FMJ',
  'GP1',
  'Infernus',
  'RE7B',
  'Nero',
  'Nero2',
  'Osiris',
  'Penetrator',
  'Pfister811',
  'Prototipo',
  'Reaper',
  'Sheava',
  'Sultan RS',
  'Superd',
  'T20',
  'Tempesta',
  'Turismo2',
  'Turismor',
  'Tyrus',
  'Vacca',
  'Vagner',
  'Voltic',
  'Voltic2',
  'Zentorno',
  'Italigtb',
  'Italigtb2',
  'XA21',
  'Army Tanker',
  'Army Trailer',
  'Army Trailer2',
  'Bale Trailer',
  'Boat Trailer',
  'Cable Car',
  'Dock Trailer',
  'Grain Trailer',
  'Prop Trailer',
  'Rake Trailer',
  'TR2',
  'TR3',
  'TR4',
  'TRFlat',
  'TVTrailer',
  'Tanker',
  'Tanker2',
  'Trailer Logs',
  'Trailer Small',
  'Trailers',
  'Trailers2',
  'Trailers3',
  'Freight',
  'Freight Car',
  'Freight Cont1',
  'Freight Cont2',
  'Freight Grain',
  'Freight Trailer',
  'Tanker Car',
  'Airtug',
  'Caddy',
  'Caddy2',
  'Caddy3',
  'Docktug',
  'Forklift',
  'Mower',
  'Ripley',
  'Sadler',
  'Scrap',
  'Tow Truck',
  'Tow Truck2',
  'Tractor',
  'Tractor2',
  'Tractor3',
  'Trailer Large',
  'Trailer S4',
  'Utilli Truck',
  'Bison',
  'Bison2',
  'Bison3',
  'Bobcat XL',
  'Boxville',
  'Boxville2',
  'Boxville3',
  'Boxville4',
  'Boxville5',
  'Burrito',
  'Burrito2',
  'Burrito3',
  'Burrito4',
  'Burrito5',
  'Camper',
  'GBurrito',
  'GBurrito2',
  'Journey',
  'Minivan',
  'Minivan2',
  'Paradise',
  'Pony',
  'Pony2',
  'Rumpo',
  'Rumpo2',
  'Rumpo3',
  'Speedo',
  'Speedo2',
  'Surfer',
  'Surfer2',
  'Taco',
  'Youga',
  'Youga2',
];

const Weapons = [
  {
    type: 'melee',
    keys: [
      {
        type: 'dagger',
        keys: '0x92A27487',
      },
      {
        type: 'bat',
        keys: '0x958A4A8F',
      },
      {
        type: 'bottle',
        keys: '0xF9E6AA4B',
      },
      {
        type: 'crowbar',
        keys: '0x84BD7BFD',
      },
      {
        type: 'unarmed',
        keys: '0xA2719263',
      },
      {
        type: 'flashlight',
        keys: '0x8BB05FD7',
      },
      {
        type: 'golfclub',
        keys: '0x440E4788',
      },
      {
        type: 'hammer',
        keys: '0x4E875F73',
      },
      {
        type: 'hatchet',
        keys: '0xF9DCBF2D',
      },
      {
        type: 'knuckle',
        keys: '0xD8DF3C3C',
      },
      {
        type: 'knife',
        keys: '0x99B507EA',
      },
      {
        type: 'machete',
        keys: '0xDD5DF8D9',
      },
      {
        type: 'switchblade',
        keys: '0xDFE37640',
      },
      {
        type: 'nightstick',
        keys: '0x678B81B1',
      },
      {
        type: 'wrench',
        keys: '0x19044EE0',
      },
      {
        type: 'battleaxe',
        keys: '0xCD274149',
      },
      {
        type: 'poolcue',
        keys: '0x94117305',
      },
      {
        type: 'stone_hatchet',
        keys: '0x3813FC08',
      },
    ],
  },
  {
    type: 'handguns',
    keys: [
      {
        type: 'pistol',
        keys: '0x1B06D571',
      },
      {
        type: 'pistol_mk2',
        keys: '0xBFE256D4',
      },
      {
        type: 'combatpistol',
        keys: '0x5EF9FEC4',
      },
      {
        type: 'appistol',
        keys: '0x22D8FE39',
      },
      {
        type: 'stungun',
        keys: '0x3656C8C1',
      },
      {
        type: 'pistol50',
        keys: '0x99AEEB3B',
      },
      {
        type: 'snspistol',
        keys: '0xBFD21232',
      },
      {
        type: 'snspistol_mk2',
        keys: '0x88374054',
      },
      {
        type: 'heavypistol',
        keys: '0xD205520E',
      },
      {
        type: 'vintagepistol',
        keys: '0x83839C4',
      },
      {
        type: 'flaregun',
        keys: '0x47757124',
      },
      {
        type: 'marksmanpistol',
        keys: '0xDC4DB296',
      },
      {
        type: 'revolver',
        keys: '0xC1B3C3D1',
      },
      {
        type: 'revolver_mk2',
        keys: '0xCB96392F',
      },
      {
        type: 'doubleaction',
        keys: '0x97EA20B8',
      },
      {
        type: 'raypistol',
        keys: '0xAF3696A1',
      },
      {
        type: 'ceramicpistol',
        keys: '0x2B5EF5EC',
      },
      {
        type: 'navyrevolver',
        keys: '0x917F6C8C',
      },
    ],
  },
  {
    type: 'smg',
    keys: [
      {
        type: 'microsmg',
        keys: '0x13532244',
      },
      {
        type: 'smg',
        keys: '0x2BE6766B',
      },
      {
        type: 'smg_mk2',
        keys: '0x78A97CD0',
      },
      {
        type: 'assaultsmg',
        keys: '0xEFE7E2DF',
      },
      {
        type: 'combatpdw',
        keys: '0xA3D4D34',
      },
      {
        type: 'machinepistol',
        keys: '0xDB1AA450',
      },
      {
        type: 'minismg',
        keys: '0xBD248B55',
      },
      {
        type: 'raycarbine',
        keys: '0x476BF155',
      },
    ],
  },
  {
    type: 'shotguns',
    keys: [
      {
        type: 'pumpshotgun',
        keys: '0x1D073A89',
      },
      {
        type: 'pumpshotgun_mk2',
        keys: '0x555AF99A',
      },
      {
        type: 'sawnoffshotgun',
        keys: '0x7846A318',
      },
      {
        type: 'assaultshotgun',
        keys: '0xE284C527',
      },
      {
        type: 'bullpupshotgun',
        keys: '0x9D61E50F',
      },
      {
        type: 'musket',
        keys: '0xA89CB99E',
      },
      {
        type: 'heavyshotgun',
        keys: '0x3AABBBAA',
      },
      {
        type: 'dbshotgun',
        keys: '0xEF951FBB',
      },
      {
        type: 'autoshotgun',
        keys: '0x12E82D3D',
      },
    ],
  },
  {
    type: 'assault_rifles',
    keys: [
      {
        type: 'assaultrifle',
        keys: '0xBFEFFF6D',
      },
      {
        type: 'assaultrifle_mk2',
        keys: '0x394F415C',
      },
      {
        type: 'carbinerifle',
        keys: '0x83BF0278',
      },
      {
        type: 'carbinerifle_mk2',
        keys: '0xFAD1F1C9',
      },
      {
        type: 'advancedrifle',
        keys: '0xAF113F99',
      },
      {
        type: 'specialcarbine',
        keys: '0xC0A3098D',
      },
      {
        type: 'specialcarbine_mk2',
        keys: '0x969C3D67',
      },
      {
        type: 'bullpuprifle',
        keys: '0x7F229F94',
      },
      {
        type: 'bullpuprifle_mk2',
        keys: '0x84D6FAFD',
      },
      {
        type: 'compactrifle',
        keys: '0x624FE830',
      },
    ],
  },
  {
    type: 'machine_guns',
    keys: [
      {
        type: 'mg',
        keys: '0x9D07F764',
      },
      {
        type: 'combatmg',
        keys: '0x7FD62962',
      },
      {
        type: 'combatmg_mk2',
        keys: '0xDBBD7280',
      },
      {
        type: 'gusenberg',
        keys: '0x61012683',
      },
    ],
  },
  {
    type: 'sniper_rifles',
    keys: [
      {
        type: 'sniperrifle',
        keys: '0x5FC3C11',
      },
      {
        type: 'heavysniper',
        keys: '0xC472FE2',
      },
      {
        type: 'heavysniper_mk2',
        keys: '0xA914799',
      },
      {
        type: 'marksmanrifle',
        keys: '0xC734385A',
      },
      {
        type: 'marksmanrifle_mk2',
        keys: '0x6A6C02E0',
      },
    ],
  },
  {
    type: 'heavy_weapons',
    keys: [
      {
        type: 'rpg',
        keys: '0xB1CA77B1',
      },
      {
        type: 'grenadelauncher',
        keys: '0xA284510B',
      },
      {
        type: 'grenadelauncher_smoke',
        keys: '0x4DD2DC56',
      },
      {
        type: 'minigun',
        keys: '0x42BF8A85',
      },
      {
        type: 'firework',
        keys: '0x7F7497E5',
      },
      {
        type: 'railgun',
        keys: '0x6D544C99',
      },
      {
        type: 'hominglauncher',
        keys: '0x63AB0442',
      },
      {
        type: 'compactlauncher',
        keys: '0x781FE4A',
      },
      {
        type: 'rayminigun',
        keys: '0xB62D1F67',
      },
    ],
  },
  {
    type: 'throwables',
    keys: [
      {
        type: 'grenade',
        keys: '0x93E220BD',
      },
      {
        type: 'bzgas',
        keys: '0xA0973D5E',
      },
      {
        type: 'smokegrenade',
        keys: '0xFDBC8A50',
      },
      {
        type: 'flare',
        keys: '0x497FACC3',
      },
      {
        type: 'molotov',
        keys: '0x24B17070',
      },
      {
        type: 'stickybomb',
        keys: '0x2C3731D9',
      },
      {
        type: 'proxmine',
        keys: '0xAB564B93',
      },
      {
        type: 'snowball',
        keys: '0x787F0BB',
      },
      {
        type: 'pipebomb',
        keys: '0xBA45E8B8',
      },
      {
        type: 'ball',
        keys: '0x23C9F95C',
      },
    ],
  },
  {
    type: 'misc',
    keys: [
      {
        type: 'petrolcan',
        keys: '0x34A67B97',
      },
      {
        type: 'fireextinguisher',
        keys: '0x60EC506',
      },
      {
        type: 'parachute',
        keys: '0xFBAB5776',
      },
      {
        type: 'hazardcan',
        keys: '0xBA536372',
      },
    ],
  },
];

export { CarConstants, Weapons };
